<?php
date_default_timezone_set('Europe/London');
require('db.php');
require('core.php');

if(array_key_exists('interested', $_POST)) {
    // Form submitted, find data
    $data = doExec($_POST);
    if(!is_array($data)) {
        // If its not an array, an error occured
        die('An error occured while producing the bar chart: '.$data);
    } else {
        $question_data = $data['questions'][$_POST['interested'][0]];
        
        /* pChart library inclusions */ 
        include("pchart/class/pData.class.php"); 
        include("pchart/class/pDraw.class.php"); 
        include("pchart/class/pImage.class.php"); 
        include("pchart/class/pPie.class.php"); 

            
        // For every filter value (coloured sets)
        $group_option = $_POST['requested_group'];
            
        $chart_values = array();
        $chart_labels = array();
        
        $label_values = array();
        foreach($question_data['question_options'] as $field_opt) {
            // record the perecentage for each field value
            if(!array_key_exists($field_opt, $question_data['grouped_question_responses'][$group_option])) {
                $question_data['grouped_question_responses'][$group_option][$field_opt] = 0;
            }
            
            $label_values[$field_opt] = $question_data['grouped_question_responses'][$group_option][$field_opt];
        }
        
        foreach($label_values as $label => $value) {
            $chart_values[] = $value;
            $chart_labels[] = $label;
        }
        
        $MyData = new pData;  
        $MyData->addPoints($chart_values,"Values");  
        $MyData->addPoints($chart_labels,"Labels");  
        $MyData->setAbscissa("Labels");
        
        /* Create the pChart object */ 
        $myPicture = new pImage(1500,1000,$MyData);
        $myPicture->setFontProperties(array("FontName"=>"pchart/fonts/sans.ttf","FontSize"=>10));
        $myPicture->setShadow(TRUE,array("X"=>1,"Y"=>1,"R"=>0,"G"=>0,"B"=>0,"Alpha"=>20));
        $RectangleSettings = array('StartR' => 37, 'StartG' => 37, 'StartB' => 37, 'EndR' => 17, 'EndG' => 17, 'EndB' => 17); 
        $myPicture->drawGradientArea(0,0,1500,75,DIRECTION_VERTICAL,$RectangleSettings);
        $myPicture->drawText(20, 30,$felix_survey_name,array("FontSize"=>12, 'R' => 255, 'G' => 255, 'B' => 255));
        $myPicture->drawText(20, 60,col2name($_POST['interested'][0]).' for '.col2name($_POST['filter'])." option: ".$_POST['requested_group'],array("FontSize"=>18, 'R' => 255, 'G' => 255, 'B' => 255));
        $myPicture->setShadow(FALSE,array("X"=>1,"Y"=>1,"R"=>0,"G"=>0,"B"=>0,"Alpha"=>20));
        $myPicture->setShadow(TRUE,array("X"=>1,"Y"=>1,"R"=>0,"G"=>0,"B"=>0,"Alpha"=>20));
        $myPicture->drawText(20, 960,'Generated by Felix Surveys Data Tool on '.date("F j, Y, g:i a") ,array("FontSize"=>10));
        $myPicture->drawText(20, 980,"© Felix Imperial - www.felixonline.co.u", array("FontSize"=>10));
        
        /* Draw the scale and the 1st chart */ 
        
        $PieChart = new pPie($myPicture,$MyData);
        $PieChart->draw3DPie(750,500,array("Radius"=>500,"DrawLabels"=>TRUE,"LabelStacked"=>TRUE,"Border"=>TRUE,"WriteValues"=>PIE_VALUE_PERCENTAGE,"ValueR"=>0,"ValueG"=>0,"ValueB"=>0));
        $myPicture->drawText(20, 120,"Chart segments indicate: ".col2name($_POST['interested'][0]),array("FontSize"=>12));
        
        if($data['filter'] != '') {
            $myPicture->drawText(20, 150,'Filter applied: '.$data['filter'],array("FontSize"=>12));
        }
        
        $myPicture->stroke();
    }
} else {
    die('Data was not passed through');
}
